// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package events

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson692db02bDecodeGithubComGui774umeTcprobePkgTcprobeEvents(in *jlexer.Lexer, out *EventSerializer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.KernelEventSerializer = new(KernelEventSerializer)
	out.ProcessContextSerializer = new(ProcessContextSerializer)
	out.NetworkInterfaceSerializer = new(NetworkInterfaceSerializer)
	out.NetlinkMessageSerializer = new(NetlinkMessageSerializer)
	out.QDiscSerializer = new(QDiscSerializer)
	out.ChainSerializer = new(ChainSerializer)
	out.BlockSerializer = new(BlockSerializer)
	out.FilterSerializer = new(FilterSerializer)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "service":
			out.Service = string(in.String())
		case "event":
			if in.IsNull() {
				in.Skip()
				out.KernelEventSerializer = nil
			} else {
				if out.KernelEventSerializer == nil {
					out.KernelEventSerializer = new(KernelEventSerializer)
				}
				(*out.KernelEventSerializer).UnmarshalEasyJSON(in)
			}
		case "process":
			if in.IsNull() {
				in.Skip()
				out.ProcessContextSerializer = nil
			} else {
				if out.ProcessContextSerializer == nil {
					out.ProcessContextSerializer = new(ProcessContextSerializer)
				}
				(*out.ProcessContextSerializer).UnmarshalEasyJSON(in)
			}
		case "network_interface":
			if in.IsNull() {
				in.Skip()
				out.NetworkInterfaceSerializer = nil
			} else {
				if out.NetworkInterfaceSerializer == nil {
					out.NetworkInterfaceSerializer = new(NetworkInterfaceSerializer)
				}
				(*out.NetworkInterfaceSerializer).UnmarshalEasyJSON(in)
			}
		case "netlink_message":
			if in.IsNull() {
				in.Skip()
				out.NetlinkMessageSerializer = nil
			} else {
				if out.NetlinkMessageSerializer == nil {
					out.NetlinkMessageSerializer = new(NetlinkMessageSerializer)
				}
				(*out.NetlinkMessageSerializer).UnmarshalEasyJSON(in)
			}
		case "qdisc":
			if in.IsNull() {
				in.Skip()
				out.QDiscSerializer = nil
			} else {
				if out.QDiscSerializer == nil {
					out.QDiscSerializer = new(QDiscSerializer)
				}
				(*out.QDiscSerializer).UnmarshalEasyJSON(in)
			}
		case "chain":
			if in.IsNull() {
				in.Skip()
				out.ChainSerializer = nil
			} else {
				if out.ChainSerializer == nil {
					out.ChainSerializer = new(ChainSerializer)
				}
				(*out.ChainSerializer).UnmarshalEasyJSON(in)
			}
		case "block":
			if in.IsNull() {
				in.Skip()
				out.BlockSerializer = nil
			} else {
				if out.BlockSerializer == nil {
					out.BlockSerializer = new(BlockSerializer)
				}
				(*out.BlockSerializer).UnmarshalEasyJSON(in)
			}
		case "filter":
			if in.IsNull() {
				in.Skip()
				out.FilterSerializer = nil
			} else {
				if out.FilterSerializer == nil {
					out.FilterSerializer = new(FilterSerializer)
				}
				(*out.FilterSerializer).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson692db02bEncodeGithubComGui774umeTcprobePkgTcprobeEvents(out *jwriter.Writer, in EventSerializer) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Service != "" {
		const prefix string = ",\"service\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Service))
	}
	if in.KernelEventSerializer != nil {
		const prefix string = ",\"event\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.KernelEventSerializer).MarshalEasyJSON(out)
	}
	if in.ProcessContextSerializer != nil {
		const prefix string = ",\"process\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.ProcessContextSerializer).MarshalEasyJSON(out)
	}
	if in.NetworkInterfaceSerializer != nil {
		const prefix string = ",\"network_interface\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.NetworkInterfaceSerializer).MarshalEasyJSON(out)
	}
	if in.NetlinkMessageSerializer != nil {
		const prefix string = ",\"netlink_message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.NetlinkMessageSerializer).MarshalEasyJSON(out)
	}
	if in.QDiscSerializer != nil {
		const prefix string = ",\"qdisc\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.QDiscSerializer).MarshalEasyJSON(out)
	}
	if in.ChainSerializer != nil {
		const prefix string = ",\"chain\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.ChainSerializer).MarshalEasyJSON(out)
	}
	if in.BlockSerializer != nil {
		const prefix string = ",\"block\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.BlockSerializer).MarshalEasyJSON(out)
	}
	if in.FilterSerializer != nil {
		const prefix string = ",\"filter\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.FilterSerializer).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventSerializer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson692db02bEncodeGithubComGui774umeTcprobePkgTcprobeEvents(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventSerializer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson692db02bDecodeGithubComGui774umeTcprobePkgTcprobeEvents(l, v)
}
