// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package events

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson408a5efDecodeGithubComGui774umeTcprobePkgTcprobeEvents(in *jlexer.Lexer, out *NetlinkMessageSerializer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.NetlinkMessage = new(NetlinkMessage)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "flags":
			out.Flags = string(in.String())
		case "type":
			out.Type = RoutingMessageType(in.Uint16())
		case "error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson408a5efEncodeGithubComGui774umeTcprobePkgTcprobeEvents(out *jwriter.Writer, in NetlinkMessageSerializer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix[1:])
		out.String(string(in.Flags))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.Raw((in.Type).MarshalJSON())
	}
	if in.Error != "" {
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NetlinkMessageSerializer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson408a5efEncodeGithubComGui774umeTcprobePkgTcprobeEvents(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NetlinkMessageSerializer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson408a5efDecodeGithubComGui774umeTcprobePkgTcprobeEvents(l, v)
}
