// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package events

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson67024250DecodeGithubComGui774umeTcprobePkgTcprobeEvents(in *jlexer.Lexer, out *QDiscEventSerializer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.QDiscEvent = new(QDiscEvent)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "netlink_message_flags":
			out.NetlinkMessageFlags = string(in.String())
		case "netns":
			out.Netns = uint32(in.Uint32())
		case "ifindex":
			out.IfIndex = uint32(in.Uint32())
		case "ifname":
			out.IfName = string(in.String())
		case "handle":
			out.Handle = Handle(in.Uint32())
		case "parent":
			out.Parent = Handle(in.Uint32())
		case "qdisc_id":
			out.QDiscID = string(in.String())
		case "netlink_message_type":
			out.NetlinkMessageType = RoutingMessageType(in.Uint16())
		case "netlink_error_message":
			out.NetlinkErrorMessage = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson67024250EncodeGithubComGui774umeTcprobePkgTcprobeEvents(out *jwriter.Writer, in QDiscEventSerializer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"netlink_message_flags\":"
		out.RawString(prefix[1:])
		out.String(string(in.NetlinkMessageFlags))
	}
	{
		const prefix string = ",\"netns\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Netns))
	}
	{
		const prefix string = ",\"ifindex\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.IfIndex))
	}
	{
		const prefix string = ",\"ifname\":"
		out.RawString(prefix)
		out.String(string(in.IfName))
	}
	{
		const prefix string = ",\"handle\":"
		out.RawString(prefix)
		out.Raw((in.Handle).MarshalJSON())
	}
	{
		const prefix string = ",\"parent\":"
		out.RawString(prefix)
		out.Raw((in.Parent).MarshalJSON())
	}
	{
		const prefix string = ",\"qdisc_id\":"
		out.RawString(prefix)
		out.String(string(in.QDiscID))
	}
	{
		const prefix string = ",\"netlink_message_type\":"
		out.RawString(prefix)
		out.Raw((in.NetlinkMessageType).MarshalJSON())
	}
	if in.NetlinkErrorMessage != "" {
		const prefix string = ",\"netlink_error_message\":"
		out.RawString(prefix)
		out.String(string(in.NetlinkErrorMessage))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v QDiscEventSerializer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson67024250EncodeGithubComGui774umeTcprobePkgTcprobeEvents(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *QDiscEventSerializer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson67024250DecodeGithubComGui774umeTcprobePkgTcprobeEvents(l, v)
}
